
services:
  db:
    image: mongo:5
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
